# Generated by Django 4.1 on 2023-10-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economical_data', '0002_interestrate_time_scraped'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLF_interestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='InterestRate',
        ),
    ]
