# Generated by Django 4.1 on 2023-10-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economical_data', '0003_mlf_interestrate_delete_interestrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KEY', models.CharField(max_length=255)),
                ('TIME_PERIOD', models.DateField()),
                ('OBS_VALUE', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='MLF_interestRate',
        ),
    ]
