# Generated by Django 4.1 on 2023-10-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economical_data', '0004_generalfinancialdata_delete_mlf_interestrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalfinancialdata',
            old_name='KEY',
            new_name='TITLE',
        ),
    ]
